"""initial schema

Revision ID: accd0368ffc2
Revises: 
Create Date: 2026-08-28 17:04:31.380585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'accd0368ffc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turbines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='technician', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turbine_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='inspection_status'), server_default='queued', nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turbine_id'], ['turbines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_pending', 'inspections', ['status'], unique=False, postgresql_where=sa.text("status IN ('queued','processing')"))
    op.create_index('ix_inspections_turbine_created', 'inspections', ['turbine_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('blade_side', sa.Enum('leading_edge', 'trailing_edge', 'suction', 'pressure', name='blade_side'), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_index('ix_images_inspection', 'images', ['inspection_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('pdf_key', sa.String(length=512), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('damage_class', sa.Enum('crack', 'erosion', 'lightning_strike', 'delamination', name='damage_class'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_w', sa.Float(), nullable=False),
    sa.Column('bbox_h', sa.Float(), nullable=False),
    sa.Column('area_ratio', sa.Float(), sa.Computed('bbox_w * bbox_h', persisted=True), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bbox_h > 0 AND bbox_h <= 1', name='ck_detection_bbox_h'),
    sa.CheckConstraint('bbox_w > 0 AND bbox_w <= 1', name='ck_detection_bbox_w'),
    sa.CheckConstraint('bbox_x >= 0 AND bbox_x <= 1', name='ck_detection_bbox_x'),
    sa.CheckConstraint('bbox_y >= 0 AND bbox_y <= 1', name='ck_detection_bbox_y'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_detection_confidence'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_image', 'detections', ['image_id'], unique=False)
    op.create_index('ix_detections_severity_class', 'detections', ['severity', 'damage_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detections_severity_class', table_name='detections')
    op.drop_index('ix_detections_image', table_name='detections')
    op.drop_table('detections')
    op.drop_table('reports')
    op.drop_index('ix_images_inspection', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_inspections_turbine_created', table_name='inspections')
    op.drop_index('ix_inspections_pending', table_name='inspections', postgresql_where=sa.text("status IN ('queued','processing')"))
    op.drop_table('inspections')
    op.drop_table('users')
    op.drop_table('turbines')
    # ### end Alembic commands ###
